version: '3.8'

networks:
    default:
        name: project-network

services:

        final_project:
            build:
                context: ./php-fpm
                args:
                    - timezone=${TZ}
            volumes:
                - ./../final_project:/final_project:rw,cached
                - final_project_log:/final_project/var/log
            env_file:
                - .env
            depends_on:
                - redis
                - mysql

        nginx:
            container_name: nginx
            build:
                context: ./nginx
                args:
                    - timezone=${TZ}
            ports:
                - "8080:80"
                - "443:443"
            depends_on:
                - final_project
            volumes:
                - ./../final_project/public:/final_project/public
                - ./nginx/ssl:/etc/nginx/ssl
                - ./nginx/conf.d:/etc/nginx/conf.d
                - ./nginx/nginx_log:/var/log/nginx
                - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            env_file:
                - .env
            command: /bin/bash -c "exec nginx -g 'daemon off;'"

        redis:
            container_name: redis
            image: redis:latest
            ports:
                - "6379:6379"

        mysql:
            container_name: mysql
            image: mysql:latest
            env_file:
                - db/master/.env.master
            ports:
                - "3307:3306"
            volumes:
                - ./db/master/.data/mysql:/var/lib/mysql:rw

        mailhog:
            image: mailhog/mailhog:v1.0.1
            container_name: mail-hog
            depends_on:
                - mysql
            ports:
                - 8025:8025

volumes:
    nginx_log:
    final_project_log:
    db:
        driver: local
